spring:
  application:
    name: usuario-producer
  cloud:
    stream:
      bindings:
        output:
          #destination: usuario-stream
          destination: demo
      kafka:
        binder:
          brokers: 
          - ec2-18-231-74-189.sa-east-1.compute.amazonaws.com:9092


          